apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do
  namespace: default
spec:
  replicas: 6
  selector:
    matchLabels:
      app: to-do
  template:
    metadata:
      labels:
        app: to-do
    spec:
      containers:
        - name: to-do-container
          image: manishaag7/to-do-multiimage
          imagePullPolicy: Always
          ports:
            - containerPort: 80
