apiVersion: v1
kind: Service
metadata:
  name: to-do-service
  labels:
    app: to-do
spec:
  type: LoadBalancer
  selector:
    app: to-do
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
